Repository ms1498/groupSoftwareProject, pull requests merged in 2025-03, with the labels that each got.

#79 Added attended field to Booking model
  app/models.py
Labels: enhancement

#92 Sign out UI changes
  app/templates/sign_in.html
  app/urls.py
  app/views.py
Labels: enhancement

#90 Parsing of checkin urls
  app/models.py
  app/templates/home.html
  app/urls.py
  app/views.py
  mysite/algorithms.py
  mysite/settings.py
Labels: enhancement

#85 Fixed image ui scaling
  app/templates/approval.html
  app/templates/discover.html
  app/templates/my_events.html
Labels: bug

#97 Unit test the discover page search priority calculation
  app/tests.py
  app/views.py
  mysite/algorithms.py
Labels: enhancement, refactor

#98 Allow users to view all data related to them
  app/templates/sign_in.html
  app/templates/user_data.html
  app/urls.py
  app/views.py
Labels: enhancement

#91 Badges page
  app/admin.py
  app/models.py
  app/templates/badges.html
  app/templates/base.html
  app/urls.py
  app/views.py
Labels: enhancement

#96 Fixed and reformatted the home page
  app/templates/home.html
  app/views.py
Labels: bug

#81 Fixed formatting of sign up page
  app/templates/sign_up.html
Labels: bug

#94 Stop soc reps from editing events they should not be able to access
  app/views.py
Labels: bug

#103 Changed favicon from .ico to .png
  app/static/favicon.ico
  app/static/favicon.png
  app/templates/base.html
Labels: bug

#102 Allow users to delete their accounts
  app/forms.py
  app/templates/delete_account.html
  app/templates/sign_in.html
  app/urls.py
  app/views.py
  mysite/algorithms.py
Labels: enhancement

#99 Organise UI restyling
  app/templates/edit_event.html
  app/views.py
Labels: enhancement

#105 Fixed the UI for this page
  app/templates/my_events.html
Labels: bug

#106 Added location back to the organise page
  app/templates/edit_event.html
Labels: enhancement

#78 Added date and time check to Unregister button
  README.md
  app/templates/discover.html
Labels: enhancement

#104 Badge Awarding
  app/models.py
  app/templates/discover.html
  app/views.py
  mysite/algorithms.py
  resources/db.sqlite3
  resources/readme.txt
Labels: enhancement

#101 Remodelled the discover page
  app/models.py
  app/templates/discover.html
Labels: bug

#108 Fixed two errors
  app/models.py
  app/templates/base.html
  app/views.py
Labels: bug

#107 Analytics page creation
  app/templates/edit_event.html
  app/templates/events_analytics.html
  app/urls.py
  app/views.py
Labels: enhancement

#109 Made aestetic changes to leaderboard
  app/templates/leaderboard.html
  app/views.py
Labels: enhancement

#100 Approve events img fix
  app/templates/approval.html
  app/urls.py
  app/views.py
Labels: enhancement

#110 Add checkin validation tests
  app/models.py
  app/tests.py
  app/views.py
  mysite/algorithms.py
Labels: enhancement

#111 Fix word wrap on discover page
  app/templates/discover.html
Labels: bug

#115 Give student permission to Student accounts in the database
  resources/db.sqlite3
Labels: bug

#113 Fixing the sidebar and allowing society reps to set number of tickets
  app/forms.py
  app/models.py
  app/templates/edit_event.html
  app/templates/events_analytics.html
  app/templates/organise.html
  app/views.py
Labels: bug

#116 Update README.md to include the URL to access our hosted version of the app
  README.md
Labels: documentation

#118 Added Default Event Image
  app/static/default-event.jpg
Labels: bug

#114 Changed navbar formatting + highlights
  app/templates/base.html
Labels: bug

#117 Fix login redirect
  app/views.py
  mysite/settings.py
Labels: bug

#122 Adjusted order of buttons so they dont look off centre on small screen
  app/templates/home.html
Labels: bug

#119 Fixed the signup page so form only appears once
  app/templates/sign_up.html
Labels: bug

#121 Added Deployment Section to ReadMe
  README.md
Labels: documentation

#120 Background design
  app/static/vines.png
  app/templates/home.html
Labels: enhancement

#123 Technical documentation
  technical_documentation.md
Labels: documentation

#124 Fixed the nav bar so all items are inline
  app/templates/base.html
  app/templates/leaderboard.html
Labels: enhancement

#127 Fix data view button overlapping copyright info
  app/templates/sign_in.html
Labels: bug

#130 Fix badges and accounts on example database
  app/templates/edit_event.html
  resources/db.sqlite3
Labels: bug

#128 Background images
  .DS_Store
  .gitignore
  app/templates/base.html
  media/background_images/tree_2.png
Labels: enhancement

#132 Fix/event edit form works
  app/forms.py
  app/models.py
  app/templates/edit_event.html
  app/views.py
  technical_documents/source/db.sqlite3
Labels: bug

#133 Removed unnecessary sprint 1 files
  known_issues.md
  prototype_contents.md
Labels: documentation
